[workspace]
members = [ "PictoThing", "foa_dswifi"]
resolver = "2"


[patch.crates-io]

embassy-net-driver = { version = "0.2.0",  path = "/home/bread/CLionProjects/embassy/embassy-net-driver" }
embassy-net-esp-hosted = { version = "0.2.0", path = "/home/bread/CLionProjects/embassy/embassy-net-esp-hosted" }
embassy-time-driver = { version = "0.2.0", path = "/home/bread/CLionProjects/embassy/embassy-time-driver"}

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

[profile.dev.package.esp-storage]
opt-level = 3
[profile.release.package.esp-storage]
opt-level = 3