[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor -f 80mhz -B 3000000 -C -L defmt"
#runner = "probe-rs download --chip=esp32 --speed 26000"

[env]
DEFMT_LOG="trace"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",

]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
