[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor -f 80mhz --partition-table table.csv -L defmt -s 8mb --baud 2000000"
#runner = "probe-rs download --chip=esp32 --speed 26000 --idf-partition-table table.csv"

[env]
DEFMT_LOG="info"
ESP_HAL_CONFIG_XTAL_FREQUENCY="40"
ESP_HAL_CONFIG_PSRAM_MODE="quad"
ESP_HAL_CONFIG_PLACE_SPI_MASTER_DRIVER_IN_RAM="true"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles","-Z", "stack-protector=all"
]


target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
